# Generated by Django 5.0.14 on 2025-11-11 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('rider', 'Rider'), ('driver', 'Driver')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'indexes': [models.Index(fields=['email'], name='user_email_7bbb4c_idx'), models.Index(fields=['role'], name='user_role_3744fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en-route', 'En Route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('pickup_time', models.DateTimeField()),
                ('id_driver', models.ForeignKey(db_column='id_driver', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to='rides.user')),
                ('id_rider', models.ForeignKey(db_column='id_rider', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to='rides.user')),
            ],
            options={
                'db_table': 'ride',
                'ordering': ['-pickup_time'],
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id_ride_event', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_ride', models.ForeignKey(db_column='id_ride', on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='rides.ride')),
            ],
            options={
                'db_table': 'ride_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_ride', 'created_at'], name='ride_event_id_ride_ca7133_idx'), models.Index(fields=['created_at'], name='ride_event_created_fda889_idx'), models.Index(fields=['description'], name='ride_event_descrip_3849aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='ride_status_4ce3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='ride_pickup__112ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['id_rider'], name='ride_id_ride_8b38cd_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['id_driver'], name='ride_id_driv_d151ab_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='ride_pickup__22d4cb_idx'),
        ),
    ]
